nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*'] # Autorise toutes les origines
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':  # Applique cette configuration uniquement aux routes commençant par /api
            allow_origin: ['*']  # Autorise toutes les origines pour les API
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true